CREATE TABLE QUESTIONS(ID INT PRIMARY KEY NOT NULL, TEXT CHAR(256) NOT NULL, ANSWER INT NOT NULL);
CREATE TABLE ANSWERS(ID INT PRIMARY KEY NOT NULL, TEXT CHAR(128) NOT NULL, QUESTION_ID INT NOT NULL, FOREIGN KEY (QUESTION_ID) REFERENCES QUSTIONS(ID));
CREATE TABLE USERS(ID INT PRIMARY KEY NOT NULL, USERNAME CHAR(64) NOT NULL, SCORE INT NOT NULL);